### ISSUE TITLE
Tracking issue for split

### ISSUE THREAD

**Issue by HaoboGu** [HaoboGu/rmk#61]
This is the tracking issue for split keyboard support.

- [x] Basic split BLE implementation #60 
- [x] Config split keyboard using `keyboard.toml`
- [x] Put splits to sleep mode if there's no key
- [x] Update project template
- [x] Test the power consumption
- [x] Heterogeneous split communication, dongle mode, etc
- [ ] Report battery level on both side

<details><summary>More features</summary>
<p>

After my investigation, the following features require the host connect to both left and right. They won't be implemented in the foreseeable future.

- [ ] Manually switch the master & slave role
- [ ] Auto-switch the master & slave role to avoid master's battery running out too fast
- [ ] Switch to usb if USB cable is connected to one of the splits and make it master

</p>
</details>

**Comment by HaoboGu** [comment]
Tested split power consumption:
- idle state: central=350ua, peripheral=20ua
- key pressing state: 2-3ma

**Comment by HaoboGu** [comment]
Closing this since the split has been supported for a while
