### ISSUE TITLE
Tracking issue for BLE

### ISSUE THREAD

**Issue by HaoboGu** [HaoboGu/rmk#63]
This is the tracking issue for BLE feature.

- [x] BLE implementation for nRF/ESP32
- [x] Switch between multiple BLE profiles
- [x] Real-time keymap editing over BLE
- [x] Manually switch BLE/USB mode
- [x] #206

**Comment by HaoboGu** [comment]
[ch58x](https://github.com/ch32-rs/ch58x-hal) is impossible to expose HCI interface in the foreseeable future, so BLE implementation for ch58x is removed from the list
